/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/ 

let num1 = 1; 
let num2 = 2;

let end = 4000000;

result = 0;
while (num2 <= end){
    if (num2 % 2 == 0){
        result += num2;
    }
    let temp = num1 + num2;
    num1 = num2;
    num2 = temp;
}
console.log('The sum of the even-valued terms ', result);